type Mutation {
  """
  Creates a new code golf Challenge
  """
  createChallenge(
    title: String!,
    description: String!,
    tags: [String!],
    setupCode: String!,
    testCode: String!,
    solutionCode: String!
  ): CreateChallengeResult!
    @auth(role: CREATOR)
    @rateLimit(max: 1, window: "5m")

  """
  Executes a dry run of arbitrary code golf Challenge code
  """
  testChallenge(
    setupCode: String!,
    testCode: String!,
    solutionCode: String!
  ): Result!
    @auth(role: CREATOR)
    @rateLimit(max: 5, window: "1m")

  """
  Submits a solution to a published Challenege
  """
  createSolution(
    challenge: ID!,
    solutionCode: String!
  ): CreateSolutionResult!
    @auth
    @rateLimit(max: 2, window: "1m")

  """
  Executes a dry run of a solution
  """
  testSolution(
    challenge: ID!,
    solutionCode: String!
  ): Result!
    @auth
    @rateLimit(max: 5, window: "1m")

  """
  Upvote a proposed Challenge
  """
  upvote(
    challenge: ID!
  ): Boolean!
    @auth(role: CREATOR)
    @rateLimit(max: 3, window: "1m")

  """
  Downvote a proposed Challenge with reason
  """
  downvote(
    challenge: ID!,
    reason: String
  ): Boolean!
    @auth(role: CREATOR)
    @rateLimit(max: 3, window: "1m")
}
