type Mutation {
  createChallenge(
    title: String!,
    description: String!,
    tags: [String],
    setupCode: String!,
    testCode: String!,
    referenceSolution: String!
  ): CreateChallengeResult!

  testChallenge(setupCode: String!, testCode: String!, solution: String!): Result!

  createSolution(challenge: ID!, solution: String!): CreateSolutionResult!

  testSolution(challenge: ID!, solution: String!): Result!

  upvote(challenge: ID!): Boolean!

  downvote(challenge: ID!, reason: String): Boolean!
}
