type Query {
  """
  Get a user profile by ID
  """
  getUser(
    id: ID!
  ): User

  """
  Get the currently authenticated user's profile
  """
  getOwnUser: User
    @auth

  """
  Get a challenge by ID
  """
  getChallenge(
    id: ID!
  ): Challenge

  """
  Get list of published challenges
  """
  getChallenges: [Challenge!]!

  """
  Get list of proposed challenges
  """
  getProposedChallenges: [Challenge!]!
}
