extend type Query {
  """
  Get a challenge by ID
  """
  getChallenge(
    id: ID!
  ): Challenge

  """
  Get list of published challenges
  """
  getChallenges: [Challenge!]!

  """
  Get list of proposed challenges
  """
  getProposedChallenges: [Challenge!]!

  """
  Get the currently authenticated user's draft challenges
  """
  getOwnDraftChallenges: [Challenge!]!
    @auth(role: CREATOR)
}
