mutation testChallenge(
  $setupCode: String!,
  $testCode: String!,
  $solutionCode: String!
) {
  testChallenge(
    setupCode: $setupCode,
    testCode: $testCode,
    solutionCode: $solutionCode
  ) {
    success
    errors
  }
}

mutation createChallenge(
  $title: String!,
  $description: String!,
  $tags: [String!],
  $setupCode: String!,
  $testCode: String!,
  $solutionCode: String!
) {
  createChallenge(
    title: $title,
    description: $description,
    tags: $tags,
    setupCode: $setupCode,
    testCode: $testCode,
    solutionCode: $solutionCode
  ) {
    result {
      success
      errors
    }
    challenge {
      id
    }
  }
}

mutation editDraftChallenge(
  $id: ID!,
  $title: String!,
  $description: String!,
  $tags: [String!],
  $setupCode: String!,
  $testCode: String!,
  $solutionCode: String!
) {
  editDraftChallenge(
    id: $id,
    title: $title,
    description: $description,
    tags: $tags,
    setupCode: $setupCode,
    testCode: $testCode,
    solutionCode: $solutionCode
  ) {
    result {
      success
      errors
    }
    challenge {
      id
    }
  }
}

mutation proposeChallenge(
  $id: ID!
) {
  proposeChallenge(
    id: $id
  ) {
    success
    errors
  }
}

mutation deleteOwnChallenge(
  $id: ID!
) {
  deleteOwnChallenge(
    id: $id
  )
}
