query getChallenges {
  getChallenges {
    id
    title
    published
    author { name }
    tags
  }
}

query getProposedChallenges {
  getProposedChallenges {
    id
    title
    updated
    author { name }
    tags
    upvotes
    downvotes
  }
}

query getChallenge(
  $id: ID!
) {
  getChallenge(id: $id) {
    id
    title
    published
    author {
      id
      githubId
      name
    }
    status
    tags
    description
    setupCode
    testCode
    solutions {
      timestamp
      author { name }
      size
    }
  }
}
